name: Bug report
description: Create a report to help us improve CodeIgniter Shield
title: "Bug: "
labels: ['bug']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Before you begin, **please ensure that there are no existing issues,
        whether still open or closed, related to your report**.
        If there is, your report will be closed promptly.

        For example, if you get the error "*Can't find a route for 'post: login'*",
        you can search the GitHub repository with the keyword "[Can't find a route for](https://github.com/codeigniter4/shield/issues?q=Can%27t+find+a+route+for)".

        ---

  - type: dropdown
    id: php-version
    attributes:
      label: PHP Version
      description: Which PHP versions did you run your code?
      multiple: true
      options:
        - '7.4'
        - '8.0'
        - '8.1'
    validations:
      required: true

  - type: input
    id: codeigniter-version
    attributes:
      label: CodeIgniter4 Version
      description: |
        e.g. 4.2.2
    validations:
      required: true

  - type: input
    id: shield-version
    attributes:
      label: Shield Version
      description: |
        e.g. 1.0.0-beta.2
        If you are not using the [latest version](https://github.com/codeigniter4/shield/releases), please
        check to see if the problem occurs with the latest version.
    validations:
      required: true

  - type: dropdown
    id: operating-systems
    attributes:
      label: Which operating systems have you tested for this bug?
      description: You may select more than one.
      multiple: true
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: dropdown
    id: server
    attributes:
      label: Which server did you use?
      options:
        - apache
        - cli
        - cli-server (PHP built-in webserver)
        - cgi-fcgi
        - fpm-fcgi
        - phpdbg
    validations:
      required: true

  - type: input
    id: database
    attributes:
      label: Database
      description: e.g. MySQL 5.6, MariaDB 10.2, PostgreSQL 9.6
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Output
      description: What do you expect to happen instead of this filed bug?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
