#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php$`

# Determine if a file list is passed
if [ "$#" -eq 1 ]; then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi

SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Starting CodeIgniter precommit..."

if [ "$SFILES" != "" ]; then
    echo "Linting PHP code..."
    for FILE in $SFILES; do
        php -l -d display_errors=0 "$PROJECT/$FILE"

        if [ $? != 0 ]; then
            echo "Fix the error(s) before commit."
            exit 1
        fi

        FILES="$FILES $FILE"
    done
fi

if [ "$FILES" != "" ]; then
    echo "Running PHPStan..."

    php ./vendor/bin/phpstan analyse

    if [ $? != 0 ]; then
        echo "Fix the phpstan error(s) before commit."
        exit 1
    fi
fi

if [ "$FILES" != "" ]; then
    echo "Running PHP CS Fixer..."

	./vendor/bin/php-cs-fixer fix --verbose --dry-run --using-cache=no --diff

    if [ $? != 0 ]; then
        echo "Some files are not following the coding standards. Please fix them before commit."
        exit 1
    fi
fi

exit $?
