name: Deptrac

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.php'
      - 'composer.*'
      - 'depfile.yaml'
      - '.github/workflows/deptrac.yml'
  push:
    branches:
      - develop
    paths:
      - '**.php'
      - 'composer.*'
      - 'depfile.yaml'
      - '.github/workflows/deptrac.yml'

jobs:
  deptrac:
    uses: codeigniter4/.github/.github/workflows/deptrac.yml@main
