name: Detect Merge Commits

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    name: Check for merge commits
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Run test
        uses: NexusPHP/no-merge-commits@109a3342781ddcf26b2fa739f29e8ee9f68b7d8e
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
