name: PHPCSFixer

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.php'
      - '.github/workflows/phpcsfixer.yml'
  push:
    branches:
      - develop
    paths:
      - '**.php'
      - '.github/workflows/phpcsfixer.yml'

jobs:
  phpcsfixer:
    uses: codeigniter4/.github/.github/workflows/phpcsfixer.yml@main
